"""Source-controlled Codex homes shared by worker login and telemetry.

Moved from worker_codex_adapter without changing its isolation/lifecycle rules.
Telemetry uses only path and validate; it never provisions or repairs a home.
"""

from __future__ import annotations

import os
import shutil
import stat
import threading
import time
import uuid
from pathlib import Path
from typing import cast

from .worker_identity_store import ensure_private_tree

CONTROLLED_CONFIG_NAME = "config.toml"

_CONTROLLED_CONFIG_NOTICE = (
    "# Generated by the Scarcity Router Codex execution adapter. Do not edit.\n"
    "# Controlled isolation home: no MCP servers, no plugins, no apps or\n"
    "# connectors, no trust defaults. Scarcity Router never reads credentials\n"
    "# from this home; sign in with the official CLI against CODEX_HOME.\n"
)

_HOME_MODE_OK_MASK = 0o077  # group/other bits must be absent


class ControlledCodexHome:
    """The adapter-owned, permissioned ``CODEX_HOME`` (never the user's).

    Created lazily under the worker's state area, ``0o700``, with a minimal
    generated ``config.toml``. The path is derived from the adapter's state
    directory alone; arbitrary ``CODEX_HOME`` values from outside are not
    accepted. Validity (mode and exact config content) is re-checked before
    every session so silent tampering fails closed.
    """

    def __init__(
        self,
        state_dir: str | os.PathLike[str],
        *,
        name: str = "codex",
    ) -> None:
        root = Path(state_dir) / name
        self._home: Path = root / "codex-home"
        self._scratch_root: Path = root / "scratch"
        self._lock: threading.Lock = threading.Lock()

    @property
    def path(self) -> Path:
        return self._home

    def ensure(self) -> None:
        """Create the controlled tree; raises ``OSError`` when impossible."""
        with self._lock:
            ensure_private_tree(str(self._home))
            ensure_private_tree(str(self._scratch_root))
            config = self._home / CONTROLLED_CONFIG_NAME
            if not config.exists():
                _write_private(config, _CONTROLLED_CONFIG_NOTICE)
            elif not self._config_is_contained(config.read_bytes()):
                # Codex appends project-trust entries at runtime. Keep ONLY
                # scratch-root project tables; credentials are never touched.
                self._regenerate_config_keeping_contained_projects()
            self._prune_stale_scratch()

    def _config_projects(self, content: bytes) -> tuple[bool, list[str]]:
        """Parse only project tables; nested/foreign configuration is refused."""
        import tomllib

        text = content.decode("utf-8", errors="replace")
        try:
            parsed: dict[str, object] = tomllib.loads(text)
        except tomllib.TOMLDecodeError:
            return False, []
        if set(parsed.keys()) - {"projects"}:
            return False, []
        projects: object = parsed.get("projects", {})
        if not isinstance(projects, dict):
            return False, []
        paths: list[str] = []
        for key, value in cast("dict[str, object]", projects).items():
            if not isinstance(value, dict):
                return False, []
            if set(cast("dict[str, object]", value).keys()) - {"trust_level"}:
                return False, []
            paths.append(key)
        return True, paths

    def _config_is_contained(self, content: bytes) -> bool:
        """Every project-trust entry must resolve inside this scratch root."""
        wellformed, project_paths = self._config_projects(content)
        if not wellformed:
            return False
        scratch_root = os.path.realpath(self._scratch_root)
        for project in project_paths:
            if not os.path.realpath(project).startswith(scratch_root + os.sep):
                return False
        return True

    def _regenerate_config_keeping_contained_projects(self) -> None:
        """Reset config to contained projects; never touch credential material."""
        config = self._home / CONTROLLED_CONFIG_NAME
        try:
            wellformed, project_paths = self._config_projects(config.read_bytes())
        except OSError:
            wellformed, project_paths = False, []
        kept = _CONTROLLED_CONFIG_NOTICE
        if wellformed:
            scratch_root = os.path.realpath(self._scratch_root)
            for project in project_paths:
                if os.path.realpath(project).startswith(scratch_root + os.sep):
                    kept += f'\n[projects."{project}"]\ntrust_level = "trusted"\n'
        # O_EXCL applies only to first creation; rewrite existing config in place.
        fd = os.open(config, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            _ = os.write(fd, kept.encode("utf-8"))
        finally:
            os.close(fd)

    def validate(self) -> str | None:
        """Validate existing home, scratch root and config without writing."""
        with self._lock:
            try:
                st = os.lstat(self._home)
                if not stat.S_ISDIR(st.st_mode):
                    return "codex_home_invalid"
                if st.st_mode & _HOME_MODE_OK_MASK:
                    return "codex_home_invalid"
                # The scratch root may not exist until ensure is called.
                try:
                    scratch_st = os.lstat(self._scratch_root)
                    if not stat.S_ISDIR(scratch_st.st_mode):
                        return "codex_home_invalid"
                except OSError:
                    pass
                config = self._home / CONTROLLED_CONFIG_NAME
                config_st = os.lstat(config)
                if not stat.S_ISREG(config_st.st_mode):
                    return "codex_home_invalid"
                if config_st.st_mode & _HOME_MODE_OK_MASK:
                    return "codex_home_invalid"
                if not self._config_is_contained(config.read_bytes()):
                    return "codex_home_invalid"
            except OSError:
                return "codex_home_invalid"
        return None

    def new_scratch_dir(self) -> Path:
        """One per-attempt scratch working directory (created ``0o700``)."""
        with self._lock:
            ensure_private_tree(str(self._scratch_root))
            scratch = self._scratch_root / f"turn-{uuid.uuid4().hex}"
            scratch.mkdir(mode=0o700)
            os.chmod(scratch, 0o700)
            return scratch

    def _prune_stale_scratch(self, *, max_age_seconds: float = 24 * 3600.0) -> None:
        """Best-effort bounded hygiene for scratch dirs left by crashed calls."""
        try:
            now = time.time()
            for entry in self._scratch_root.iterdir():
                try:
                    if now - entry.stat().st_mtime > max_age_seconds:
                        shutil.rmtree(entry, ignore_errors=True)
                except OSError:
                    continue
        except OSError:
            return


def _write_private(path: Path, content: str) -> None:
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        _ = os.write(fd, content.encode("utf-8"))
    finally:
        os.close(fd)
