"""First-class worker service lifecycle: the systemd USER unit manager (#138).

One paired Linux/WSL worker runs as a normal OS service through a
generated systemd **user** unit — no root, no system unit, no second
worker launcher. This module owns the whole lifecycle surface of
``scarcity-router-worker service install|status|restart|uninstall``:

- **install** renders the unit from the ACTUAL installed executable
  (the console script or packaged binary this command ran through) and
  the ACTUAL worker state directory, preserving the adapter selection
  (``--codex-source`` instances, loopback Ollama, ZCode sources, or the
  legacy single-Codex flags) as ``ExecStart`` arguments. It operates on
  the already-paired identity and uses the STORED server origin — there
  is no ``--server`` here. The unit embeds no credential: pairing
  identity, provider-controlled homes and rotation state all live in the
  0700 state directory the unit merely points at.
- **Idempotent and honest.** The rendered unit is deterministic
  (byte-stable for identical inputs): re-running install with the same
  flags re-writes nothing and stays green. A DIFFERENT generated unit
  replaces the previous one (the documented configuration-update path,
  applied by ``service restart``). An existing unit that was NOT
  generated by us is never touched — install refuses with the removal
  recipe instead of silently clobbering an unrelated unit or a
  hand-edited copy of the retired ``examples/`` unit.
- **systemd owns the daemon.** No self-daemonizing logic: the unit runs
  the ordinary ``run`` command in the foreground under the user manager,
  ``Restart=on-failure`` covers process death (the runtime's own bounded
  reconnect backoff covers connection loss), SIGTERM reaches the
  runtime's deterministic stop path, and logs land in the journal.
  ``loginctl linger`` is handled deliberately and visibly: install
  reports the state and attempts to enable it for the invoking user,
  and a failure is a visible remediation-bearing warning — never a
  silent pass and never a hard failure of the install itself.
- **One worker per state directory, enforced.** The lifetime
  single-instance lock (:class:`scarcity_router.worker_local_store.WorkerStateDirLock`)
  makes a foreground worker and the service worker mutually exclusive;
  the second process fails closed with a useful message.

Security boundaries kept intact (D-044; the #138 comment on worker
transport): the worker origin is never an install input, so service
tooling can neither introduce a plaintext non-loopback origin nor weaken
verified-TLS ``srws://`` requirements — it reuses exactly the stored
origin ``run`` would use. No secret enters the unit file, the CLI
output, or any error message; ``systemctl``/``loginctl`` are the only
subprocesses, with no credential-bearing arguments.

Custom CA configuration is deliberately absent: child G (#139) persists
CA trust through the supported worker configuration; unit files never
carry ad-hoc ``SSL_CERT_FILE`` shell hacks.

Non-goals (issue #138): Windows service mechanics (the M10 tray remains
the Windows path), root/system units, our own daemonizing logic, and
configuration migration. One service unit per user account is the
supported shape; a second worker on one host is a second user account
with its own state directory and service.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import cast

from .worker_local_store import WorkerLocalStore, default_worker_state_dir

#: Opens the worker store for one state directory (injected by the CLI,
#: which owns the ``worker_client`` seam — this module never imports it,
#: so the runtime and its lifecycle manager cannot form an import cycle).
StoreOpener = Callable[[str], WorkerLocalStore]

#: Validates one run-style flag mapping against the real registry rules
#: (injected by the CLI; ``build_registry`` in production).
RegistryBuilder = Callable[..., object]

#: The fixed user-unit name: one worker service per user account.
SERVICE_UNIT_NAME = "scarcity-router-worker.service"

#: First line of every unit this tooling generates; the ONLY marker that
#: makes an existing unit ours to replace or remove.
UNIT_MARKER_LINE = (
    "# Managed by Scarcity Router - generated by "
    + "'scarcity-router-worker service install'; do not edit, regenerate."
)

#: Where the generated unit points for operational documentation.
DOCUMENTATION_URL = (
    "https://github.com/creatidy/scarcity-router"
    + "#deploying-the-optional-execution-gateway"
)


class ServiceToolError(Exception):
    """A required service-management binary is unavailable (safe message)."""


class ServiceExecutableError(Exception):
    """The installed worker executable could not be resolved (safe message)."""


@dataclass(frozen=True)
class ServiceToolResult:
    """One captured service-tool invocation (no secrets ever pass here)."""

    command: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str


#: The ``systemctl``/``loginctl`` seam: one captured subprocess call.
ServiceTool = Callable[[list[str]], ServiceToolResult]


@dataclass(frozen=True)
class ServiceTools:
    """The injected service-management tools (tests substitute fakes)."""

    systemctl: ServiceTool
    loginctl: ServiceTool


# ── Adapter selection carried into the unit ───────────────────────────────────


@dataclass(frozen=True)
class ServiceSelection:
    """The adapter-selection flags the unit's ``ExecStart`` preserves.

    Exactly the ``run`` adapter-selection flags (never ``--server`` or
    ``--label``: the service uses the stored origin and the pairing-time
    identity). Defaults are normalized away so an equivalent re-install
    renders the identical unit.
    """

    codex_sources: tuple[str, ...] = ()
    codex_bin: str | None = None
    zcode_sources: tuple[str, ...] = ()
    zcode_bin: str | None = None
    zcode_workspace: str | None = None
    allow_ollama: bool = False
    resource: str | None = None
    ollama_host: str | None = None
    ollama_port: int | None = None
    allow_codex: bool = False
    codex_model: str | None = None
    codex_resource: str | None = None

    @classmethod
    def from_arguments(cls, arguments: Mapping[str, object]) -> "ServiceSelection":
        """Extract the selection from parsed CLI arguments (no validation)."""

        def string(key: str) -> str | None:
            value = arguments.get(key)
            return value if isinstance(value, str) and value else None

        def strings(key: str) -> tuple[str, ...]:
            value = arguments.get(key)
            if not isinstance(value, list):
                return ()
            items = cast("list[object]", value)
            return tuple(
                item for item in items if isinstance(item, str) and item
            )

        raw_port = arguments.get("ollama_port")
        port: int | None = None
        if isinstance(raw_port, int) and not isinstance(raw_port, bool):
            if raw_port != 11434:
                port = raw_port
        raw_host = string("ollama_host")
        return cls(
            codex_sources=strings("codex_sources"),
            codex_bin=string("codex_bin"),
            zcode_sources=strings("zcode_sources"),
            zcode_bin=string("zcode_bin"),
            zcode_workspace=string("zcode_workspace"),
            allow_ollama=bool(arguments.get("allow_ollama")),
            resource=string("resource"),
            ollama_host=None if raw_host in (None, "127.0.0.1") else raw_host,
            ollama_port=port,
            allow_codex=bool(arguments.get("allow_codex")),
            codex_model=string("codex_model"),
            codex_resource=string("codex_resource"),
        )

    def as_run_arguments(self) -> dict[str, object]:
        """The run-style flag mapping for ``build_registry`` validation."""
        return {
            "allow_ollama": self.allow_ollama,
            "resource": self.resource,
            "ollama_host": self.ollama_host,
            "ollama_port": self.ollama_port,
            "allow_codex": self.allow_codex,
            "codex_model": self.codex_model,
            "codex_resource": self.codex_resource,
            "codex_sources": list(self.codex_sources),
            "codex_bin": self.codex_bin,
            "zcode_sources": list(self.zcode_sources),
            "zcode_bin": self.zcode_bin,
            "zcode_workspace": self.zcode_workspace,
        }

    def exec_start_arguments(self) -> list[str]:
        """The selection as ``run`` arguments, in one fixed order."""
        arguments: list[str] = []
        for source_id in self.codex_sources:
            arguments += ["--codex-source", source_id]
        if self.codex_bin is not None:
            arguments += ["--codex-bin", self.codex_bin]
        for source_id in self.zcode_sources:
            arguments += ["--zcode-source", source_id]
        if self.zcode_bin is not None:
            arguments += ["--zcode-bin", self.zcode_bin]
        if self.zcode_workspace is not None:
            arguments += ["--zcode-workspace", self.zcode_workspace]
        if self.allow_ollama:
            if not self.resource:
                raise ValueError("--resource is required with --allow-ollama")
            arguments += ["--allow-ollama", "--resource", self.resource]
            if self.ollama_host is not None:
                arguments += ["--ollama-host", self.ollama_host]
            if self.ollama_port is not None:
                arguments += ["--ollama-port", str(self.ollama_port)]
        if self.allow_codex:
            if not self.codex_model:
                raise ValueError("--codex-model is required with --allow-codex")
            arguments += ["--allow-codex", "--codex-model", self.codex_model]
            if self.codex_resource is not None:
                arguments += ["--codex-resource", self.codex_resource]
        return arguments


# ── Unit rendering ────────────────────────────────────────────────────────────

_SAFE_UNQUOTED = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_./:@%^+=,-"
)


def systemd_quote(word: str) -> str:
    """One ``ExecStart`` word in systemd's own quoting rules.

    Unquoted when it consists solely of characters systemd treats
    literally; otherwise double-quoted with C-style escapes for the
    characters systemd would reinterpret. Applied to every path so a
    state directory or workspace with spaces renders a VALID unit, and
    so no value can break out of its word (quotes and backslashes are
    escaped, never passed through).
    """
    if word and all(character in _SAFE_UNQUOTED for character in word):
        return word
    escaped = word.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_unit(
    *,
    executable: Path,
    state_dir: Path,
    selection: ServiceSelection,
) -> str:
    """The deterministic systemd user unit for one paired worker.

    Byte-stable for identical inputs (no timestamps), so idempotency is
    plain content equality. No secret appears anywhere: the pairing
    credential lives only inside the state directory the unit points at.
    """
    argv = [str(executable), "run", "--state-dir", str(state_dir)]
    argv += selection.exec_start_arguments()
    exec_start = " ".join(systemd_quote(word) for word in argv)
    write_paths = [str(state_dir)]
    if selection.zcode_workspace and selection.zcode_workspace not in write_paths:
        # A ZCode source executes edits in its authorized workspace, which
        # usually sits OUTSIDE the state directory: ProtectHome=read-only
        # needs this explicit write exception or every workspace edit fails.
        write_paths.append(selection.zcode_workspace)
    read_write_paths = " ".join(systemd_quote(path) for path in write_paths)
    lines = [
        UNIT_MARKER_LINE,
        "# The worker's pairing credential lives only in the state directory",
        "# (0700 tree, 0600 files); no secret is embedded in this unit.",
        "",
        "[Unit]",
        "Description=Scarcity Router native worker (outbound bridge to the router server)",
        f"Documentation={DOCUMENTATION_URL}",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=simple",
        f"ExecStart={exec_start}",
        "# The runtime reconnects with bounded backoff on its own; this",
        "# restart covers process death (crash, exhausted reconnect budget).",
        "Restart=on-failure",
        "RestartSec=5s",
        "# SIGTERM takes the deterministic stop path (stop event, socket",
        "# closed, in-flight attempts cancelled and reported interrupted).",
        "TimeoutStopSec=30s",
        "# Hardening: outbound TCP only; writes are confined to the worker",
        "# state directory (and a configured ZCode workspace).",
        "NoNewPrivileges=true",
        "PrivateTmp=true",
        "ProtectSystem=strict",
        "ProtectHome=read-only",
        f"ReadWritePaths={read_write_paths}",
        "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines)


def unit_install_path(
    *,
    env: Mapping[str, str] | None = None,
    home: Callable[[str], str] | None = None,
) -> Path:
    """The systemd user-unit location: ``$XDG_CONFIG_HOME`` or
    ``~/.config/systemd/user/<unit>`` (the same resolution as
    ``worker_state_dir``, with config in place of data)."""
    environment = os.environ if env is None else env
    xdg_config_home = environment.get("XDG_CONFIG_HOME", "")
    if xdg_config_home and os.path.isabs(xdg_config_home):
        base = Path(xdg_config_home)
    else:
        home_value = environment.get("HOME", "")
        if home_value:
            base = Path(home_value) / ".config"
        else:
            resolve_home = home if home is not None else os.path.expanduser
            base = Path(resolve_home("~")) / ".config"
    return base / "systemd" / "user" / SERVICE_UNIT_NAME


# ── Executable resolution ─────────────────────────────────────────────────────


def resolve_worker_executable(
    argv0: str | None,
    path_lookup: Callable[[str], str | None] = shutil.which,
) -> Path:
    """The ACTUAL installed worker executable for ``ExecStart``.

    The console script or packaged binary this command ran through, when
    it can be used directly (systemd user units have a minimal PATH, so
    the unit carries the resolved absolute path); under
    ``python -m scarcity_router.worker_client`` this falls back to the
    ``scarcity-router-worker`` console script on PATH.
    """
    if argv0:
        invoked = Path(argv0).name
        if invoked == "scarcity-router-worker" or invoked.startswith(
            "scarcity-worker"
        ):
            candidate = Path(argv0).resolve()
            _validate_executable(candidate)
            return candidate
    found = path_lookup("scarcity-router-worker")
    if found is None:
        raise ServiceExecutableError(
            "could not locate the installed worker executable; install the "
            + "package first (uv tool install scarcity-router or pipx "
            + "install scarcity-router) so `scarcity-router-worker` is on PATH"
        )
    candidate = Path(found).resolve()
    _validate_executable(candidate)
    return candidate


def _validate_executable(path: Path) -> None:
    if not path.is_file() or not os.access(path, os.X_OK):
        raise ServiceExecutableError(
            f"the resolved worker executable is not an executable file: {path}"
        )


# ── Tool seams ────────────────────────────────────────────────────────────────


def _service_tool(binary: str, prefix: tuple[str, ...] = ()) -> ServiceTool:
    resolved = shutil.which(binary)
    if resolved is None:
        raise ServiceToolError(
            f"{binary} was not found on PATH; the worker service lifecycle "
            + "requires a systemd user manager (Linux/WSL with systemd "
            + "enabled)"
        )

    def run(arguments: list[str]) -> ServiceToolResult:
        completed = subprocess.run(
            [resolved, *prefix, *arguments],
            capture_output=True,
            text=True,
            check=False,
        )
        raw_args = cast("list[str]", completed.args)
        return ServiceToolResult(
            command=tuple(raw_args),
            returncode=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )

    return run


def default_service_tools() -> ServiceTools:
    """The real ``systemctl --user`` / ``loginctl`` pair."""
    return ServiceTools(
        systemctl=_service_tool("systemctl", ("--user",)),
        loginctl=_service_tool("loginctl"),
    )


def _print_tool_failure(result: ServiceToolResult) -> None:
    detail = result.stderr.strip() or result.stdout.strip()
    suffix = f": {detail}" if detail else f" (exit {result.returncode})"
    print(f"worker service: systemctl failed{suffix}", file=sys.stderr)


# ── Lifecycle operations ──────────────────────────────────────────────────────


def _resolved_state_dir(arguments: Mapping[str, object]) -> Path:
    raw = arguments.get("state_dir")
    if isinstance(raw, str) and raw:
        return Path(raw).resolve()
    return Path(default_worker_state_dir()).resolve()


def install_service(
    arguments: Mapping[str, object],
    *,
    argv0: str | None,
    tools: ServiceTools,
    open_store: StoreOpener,
    build_registry: RegistryBuilder,
    unit_path: Path | None = None,
) -> int:
    """Generate (or keep) the unit, then daemon-reload + enable --now.

    ``unit_path`` overrides the resolved user-unit location (test seam;
    production always passes ``None`` and installs to the real per-user
    systemd directory). ``open_store`` and ``build_registry`` are the
    CLI-owned worker seams (pairing check and selection validation).
    """
    state_dir = _resolved_state_dir(arguments)
    store = open_store(str(state_dir))
    try:
        identity = store.load_identity()
    finally:
        store.close()
    if identity is None:
        print(
            "worker: this worker is not paired yet; pair first — service "
            + "install operates on the paired identity and uses the stored "
            + "server origin",
            file=sys.stderr,
        )
        return 2
    selection = ServiceSelection.from_arguments(arguments)
    # Validate the EXACT configuration the unit will carry, through the
    # same builder `run` uses — an invalid selection never reaches disk.
    _ = build_registry(selection.as_run_arguments(), state_dir=str(state_dir))
    executable = resolve_worker_executable(argv0)
    unit_text = render_unit(
        executable=executable, state_dir=state_dir, selection=selection
    )
    target = unit_path if unit_path is not None else unit_install_path()
    existing = (
        target.read_text(encoding="utf-8") if target.is_file() else None
    )
    if (
        existing is not None
        and existing != unit_text
        and not existing.startswith(UNIT_MARKER_LINE)
    ):
        print(
            "worker: refusing to overwrite an existing unit this tooling "
            + f"did not generate: {target}. Inspect it; if it is an old "
            + "manual copy (formerly examples/scarcity-router-worker.service), "
            + "remove it and run this command again.",
            file=sys.stderr,
        )
        return 2
    if existing == unit_text:
        print(f"worker service: unit already installed (unchanged): {target}")
    else:
        _atomic_write(target, unit_text)
        print(f"worker service: unit written: {target}")
    reloaded = tools.systemctl(["daemon-reload"])
    if reloaded.returncode != 0:
        _print_tool_failure(reloaded)
        return 2
    started = tools.systemctl(["enable", "--now", SERVICE_UNIT_NAME])
    if started.returncode != 0:
        _print_tool_failure(started)
        return 2
    print(f"worker service: enabled and started {SERVICE_UNIT_NAME}")
    _report_linger(tools)
    print(
        f"worker service: paired identity {identity.worker_id}; stored "
        + f"server origin {identity.server_origin}"
    )
    return 0


def status_service(tools: ServiceTools) -> int:
    """One linger line, then the faithful ``systemctl --user status``."""
    _print_linger_state(tools)
    result = tools.systemctl(["status", "--no-pager", SERVICE_UNIT_NAME])
    if result.stdout:
        print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    return result.returncode


def restart_service(tools: ServiceTools) -> int:
    """Restart the unit (the configuration-update application step)."""
    result = tools.systemctl(["restart", SERVICE_UNIT_NAME])
    if result.returncode == 0:
        print(f"worker service: restarted {SERVICE_UNIT_NAME}")
    else:
        if result.stdout:
            print(result.stdout, end="")
        _print_tool_failure(result)
    return result.returncode


def uninstall_service(
    tools: ServiceTools, unit_path: Path | None = None
) -> int:
    """Stop, disable and remove ONLY a unit this tooling generated.

    The paired identity and the worker state directory are deliberately
    kept (uninstalling the service is not unpairing), and linger is
    deliberately left untouched (other units may rely on it).
    """
    target = unit_path if unit_path is not None else unit_install_path()
    if not target.is_file():
        print(
            f"worker service: already uninstalled ({target} does not exist)"
        )
        return 0
    existing = target.read_text(encoding="utf-8")
    if not existing.startswith(UNIT_MARKER_LINE):
        print(
            "worker: refusing to remove a unit this tooling did not "
            + f"generate: {target}. Remove it manually if it is yours.",
            file=sys.stderr,
        )
        return 2
    stopped = tools.systemctl(["disable", "--now", SERVICE_UNIT_NAME])
    if stopped.returncode != 0:
        detail = stopped.stderr.strip() or stopped.stdout.strip()
        suffix = f": {detail}" if detail else ""
        print(
            "worker service: disable/stop reported a problem "
            + f"(continuing with the unit removal){suffix}",
            file=sys.stderr,
        )
    target.unlink()
    reloaded = tools.systemctl(["daemon-reload"])
    if reloaded.returncode != 0:
        _print_tool_failure(reloaded)
    print(
        f"worker service: uninstalled {SERVICE_UNIT_NAME}; the paired "
        + "identity and worker state were kept in the state directory; "
        + "linger was left unchanged"
    )
    return 0


# ── Linger (deliberate and visible) ───────────────────────────────────────────


def _report_linger(tools: ServiceTools) -> None:
    """Check, enable (self) and visibly report loginctl linger.

    A linger failure is NEVER an install failure — the unit is correct
    either way — but it is also never silent: the admin gets the exact
    remediation for headless operation.
    """
    uid = str(os.getuid())
    query = _tool_result_or_failure(
        tools,
        ["show-user", uid, "--property=Linger", "--value"],
    )
    if query.returncode == 0 and query.stdout.strip().lower() == "yes":
        print(
            "worker service: linger is enabled — the worker runs without "
            + "an active login session"
        )
        return
    attempt = _tool_result_or_failure(tools, ["enable-linger", uid])
    if attempt.returncode == 0:
        print(
            "worker service: linger enabled — the worker runs without an "
            + "active login session"
        )
        return
    detail = attempt.stderr.strip() or f"exit {attempt.returncode}"
    print(
        "worker service: linger is NOT enabled (" + detail + "); the "
        + "service only runs while you are logged in. For headless "
        + "operation run once: sudo loginctl enable-linger " + uid,
        file=sys.stderr,
    )


def _print_linger_state(tools: ServiceTools) -> None:
    query = _tool_result_or_failure(
        tools, ["show-user", str(os.getuid()), "--property=Linger", "--value"]
    )
    if query.returncode == 0 and query.stdout.strip().lower() == "yes":
        print("worker service: linger: enabled")
    elif query.returncode == 0:
        print(
            "worker service: linger: not enabled (the service only runs "
            + "while you are logged in; see docs for loginctl enable-linger)"
        )
    else:
        print("worker service: linger: unknown (loginctl unavailable)")


def _tool_result_or_failure(
    tools: ServiceTools, arguments: list[str]
) -> ServiceToolResult:
    try:
        return tools.loginctl(arguments)
    except ServiceToolError as exc:
        return ServiceToolResult(
            command=tuple(arguments), returncode=1, stdout="", stderr=str(exc)
        )


# ── CLI dispatch ──────────────────────────────────────────────────────────────


def run_service_command(
    arguments: Mapping[str, object],
    *,
    argv0: str | None = None,
    tools: ServiceTools | None = None,
    unit_path: Path | None = None,
    open_store: StoreOpener,
    build_registry: RegistryBuilder,
) -> int:
    """The ``service`` subcommand dispatch (the CLI's seam into here).

    Exit codes follow the worker CLI conventions: 0 success (including
    idempotent repeats), 2 refused configuration/failed operation;
    ``status``/``restart`` pass ``systemctl``'s own exit code through.
    ``argv0``, ``tools``, ``unit_path``, ``open_store`` and
    ``build_registry`` are injectable seams (tests); production resolves
    the real ones in ``worker_client.main``. A
    :class:`WorkerConfigError` from validation propagates to the CLI's
    existing typed handler.
    """
    resolved_argv0 = sys.argv[0] if argv0 is None else argv0
    resolved_tools = tools if tools is not None else default_service_tools()
    subcommand = arguments.get("service_command")
    try:
        if subcommand == "install":
            return install_service(
                arguments,
                argv0=resolved_argv0,
                tools=resolved_tools,
                open_store=open_store,
                build_registry=build_registry,
                unit_path=unit_path,
            )
        if subcommand == "status":
            return status_service(resolved_tools)
        if subcommand == "restart":
            return restart_service(resolved_tools)
        if subcommand == "uninstall":
            return uninstall_service(resolved_tools, unit_path=unit_path)
        raise ValueError(f"unknown service subcommand: {subcommand!r}")
    except (ServiceExecutableError, ServiceToolError, ValueError, OSError) as exc:
        print(f"worker: {exc}", file=sys.stderr)
        return 2


def _atomic_write(unit_path: Path, unit_text: str) -> None:
    """One atomic unit replacement (never a half-written unit on disk)."""
    unit_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = unit_path.with_name(f"{unit_path.name}.tmp-{os.getpid()}")
    try:
        _ = temporary.write_text(unit_text, encoding="utf-8")
        os.chmod(temporary, 0o644)
        os.replace(temporary, unit_path)
    except BaseException:
        try:
            temporary.unlink()
        except OSError:
            pass
        raise


__all__ = [
    "DOCUMENTATION_URL",
    "SERVICE_UNIT_NAME",
    "RegistryBuilder",
    "ServiceExecutableError",
    "ServiceSelection",
    "ServiceTool",
    "ServiceToolError",
    "ServiceToolResult",
    "ServiceTools",
    "StoreOpener",
    "UNIT_MARKER_LINE",
    "default_service_tools",
    "install_service",
    "render_unit",
    "resolve_worker_executable",
    "restart_service",
    "run_service_command",
    "status_service",
    "systemd_quote",
    "unit_install_path",
    "uninstall_service",
]
