"""First-class worker service lifecycle: the systemd USER unit manager (#138).

One paired Linux/WSL worker runs as a normal OS service through a
generated systemd **user** unit — no root, no system unit, no second
worker launcher. This module owns the whole lifecycle surface of
``scarcity-router-worker service install|status|restart|uninstall``:

- **install** renders the unit from the ACTUAL installed executable
  (the console script or packaged binary this command ran through) and
  the ACTUAL worker state directory, preserving the adapter selection
  (``--codex-source`` instances, loopback Ollama, ZCode sources, or the
  legacy single-Codex flags) as ``ExecStart`` arguments. Rendering
  follows systemd's own substitution rules: every literal ``%`` is
  doubled (specifier expansion applies to ``ExecStart`` AND
  ``ReadWritePaths``, regardless of quoting) and the ``ExecStart`` line
  suppresses ``$``-variable substitution with the documented ``:``
  executable prefix — every path stays the literal path it was rendered
  from. It operates on the already-paired identity and uses the STORED
  server origin — there is no ``--server`` here. The unit embeds no
  credential: pairing identity, provider-controlled homes and rotation
  state all live in the 0700 state directory the unit merely points at.
  A ZCode-source unit additionally excepts exactly the ZCode CLI's own
  resolved state home (``$HOME/.zcode``) from ``ProtectHome=read-only``
  — normal ZCode execution writes its session/runtime state there — so
  the write grant is worker state + that one directory + the authorized
  workspace, never a writable ``$HOME``.
- **Idempotent and honest.** The rendered unit is deterministic
  (byte-stable for identical inputs): re-running install with the same
  flags re-writes nothing and stays green. A DIFFERENT generated unit
  replaces the previous one (the documented configuration-update path,
  applied by ``service restart``). An existing unit that was NOT
  generated by us is never touched — install refuses with the removal
  recipe instead of silently clobbering an unrelated unit or a
  hand-edited copy of the retired ``examples/`` unit.
- **systemd owns the daemon.** No self-daemonizing logic: the unit runs
  the ordinary ``run`` command in the foreground under the user manager,
  ``Restart=on-failure`` covers process death (the runtime's own bounded
  reconnect backoff covers connection loss), SIGTERM reaches the
  runtime's deterministic stop path, and logs land in the journal.
  ``loginctl linger`` is handled deliberately and visibly: install
  reports the state and attempts to enable it for the invoking user,
  and a failure is a visible remediation-bearing warning — never a
  silent pass and never a hard failure of the install itself.
- **One worker per state directory, enforced.** The lifetime
  single-instance lock (:class:`scarcity_router.worker_local_store.WorkerStateDirLock`)
  makes a foreground worker and the service worker mutually exclusive;
  the second process fails closed with a useful message.
- **Install-time path discipline (Daybreak review).** Every
  filesystem-valued argument that enters the unit (``--state-dir``, the
  worker executable, ``--codex-bin``, ``--zcode-bin``,
  ``--zcode-workspace``) is resolved EXACTLY ONCE at install time to a
  canonical absolute path — the same path that was validated — so a user
  manager can never re-resolve a relative value against its own (different)
  working-directory context. The writable grants the unit declares are
  role-validated before anything is written: the filesystem root, the
  invoking user's home directory, and any grant that subsumes a protected
  boundary (the credential store, the ZCode state home) are refused with
  an actionable error. The unit itself is written through a randomized,
  exclusively created, fd-verified temporary file inside a
  trust-checked unit directory and atomically renamed — a planted
  predictable temp path or a shared config directory cannot redirect or
  clobber anything, and the lock file is opened without following
  symlinks/reparse points.

Security boundaries kept intact (D-044; the #138 comment on worker
transport): the worker origin is never an install input, so service
tooling can neither introduce a plaintext non-loopback origin nor weaken
verified-TLS ``srws://`` requirements — it reuses exactly the stored
origin ``run`` would use. No secret enters the unit file, the CLI
output, or any error message; ``systemctl``/``loginctl`` are the only
subprocesses, with no credential-bearing arguments.

Custom CA configuration is deliberately absent: child G (#139) persists
CA trust through the supported worker configuration; unit files never
carry ad-hoc ``SSL_CERT_FILE`` shell hacks.

Non-goals (issue #138): Windows service mechanics (the M10 tray remains
the Windows path), root/system units, our own daemonizing logic, and
configuration migration. One service unit per user account is the
supported shape; a second worker on one host is a second user account
with its own state directory and service.
"""

from __future__ import annotations

import os
import secrets
import shutil
import stat
import subprocess
import sys
from collections.abc import Callable, Mapping
from dataclasses import dataclass, replace
from pathlib import Path
from typing import cast

from .worker_identity_store import open_private_state_dir, open_trusted_worker_directory
from .worker_local_store import WorkerLocalStore, default_worker_state_dir
from .worker_zcode_adapter import zcode_state_home

#: Opens the worker store for one state directory (injected by the CLI,
#: which owns the ``worker_client`` seam — this module never imports it,
#: so the runtime and its lifecycle manager cannot form an import cycle).
StoreOpener = Callable[[str], WorkerLocalStore]

#: Validates one run-style flag mapping against the real registry rules
#: (injected by the CLI; ``build_registry`` in production).
RegistryBuilder = Callable[..., object]

#: The fixed user-unit name: one worker service per user account.
SERVICE_UNIT_NAME = "scarcity-router-worker.service"

#: First line of every unit this tooling generates; the ONLY marker that
#: makes an existing unit ours to replace or remove.
UNIT_MARKER_LINE = (
    "# Managed by Scarcity Router - generated by "
    + "'scarcity-router-worker service install'; do not edit, regenerate."
)

#: Where the generated unit points for operational documentation.
DOCUMENTATION_URL = (
    "https://github.com/creatidy/scarcity-router"
    + "#deploying-the-optional-execution-gateway"
)


class ServiceToolError(Exception):
    """A required service-management binary is unavailable (safe message)."""


class ServiceExecutableError(Exception):
    """The installed worker executable could not be resolved (safe message)."""


class ServiceZCodeStateHomeError(Exception):
    """The ZCode CLI state home a ZCode unit must allow is unusable.

    Raised BEFORE any unit is written: a ``ReadWritePaths`` entry that
    names a non-existent directory would make the unit fail to start at
    all, so install refuses with the remediation instead.
    """


class ServicePathError(ValueError):
    """A filesystem-valued install argument was refused before any write.

    Raised during install-time path normalization and writable-grant
    validation (the Daybreak review blockers): the message names the
    offending flag, the operator's value, the canonical path it resolves
    to and the reason, and install exits 2 without writing a unit, without
    a ``daemon-reload`` and without touching ``systemctl``.
    """


@dataclass(frozen=True)
class ServiceToolResult:
    """One captured service-tool invocation (no secrets ever pass here)."""

    command: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str


#: The ``systemctl``/``loginctl`` seam: one captured subprocess call.
ServiceTool = Callable[[list[str]], ServiceToolResult]


@dataclass(frozen=True)
class ServiceTools:
    """The injected service-management tools (tests substitute fakes)."""

    systemctl: ServiceTool
    loginctl: ServiceTool


# ── Adapter selection carried into the unit ───────────────────────────────────


@dataclass(frozen=True)
class ServiceSelection:
    """The adapter-selection flags the unit's ``ExecStart`` preserves.

    Exactly the ``run`` adapter-selection flags (never ``--server`` or
    ``--label``: the service uses the stored origin and the pairing-time
    identity). Defaults are normalized away so an equivalent re-install
    renders the identical unit.
    """

    codex_sources: tuple[str, ...] = ()
    codex_bin: str | None = None
    zcode_sources: tuple[str, ...] = ()
    zcode_bin: str | None = None
    zcode_workspace: str | None = None
    allow_ollama: bool = False
    resource: str | None = None
    ollama_host: str | None = None
    ollama_port: int | None = None
    allow_codex: bool = False
    codex_model: str | None = None
    codex_resource: str | None = None

    @classmethod
    def from_arguments(cls, arguments: Mapping[str, object]) -> "ServiceSelection":
        """Extract the selection from parsed CLI arguments (no validation)."""

        def string(key: str) -> str | None:
            value = arguments.get(key)
            return value if isinstance(value, str) and value else None

        def strings(key: str) -> tuple[str, ...]:
            value = arguments.get(key)
            if not isinstance(value, list):
                return ()
            items = cast("list[object]", value)
            return tuple(
                item for item in items if isinstance(item, str) and item
            )

        raw_port = arguments.get("ollama_port")
        port: int | None = None
        if isinstance(raw_port, int) and not isinstance(raw_port, bool):
            if raw_port != 11434:
                port = raw_port
        raw_host = string("ollama_host")
        return cls(
            codex_sources=strings("codex_sources"),
            codex_bin=string("codex_bin"),
            zcode_sources=strings("zcode_sources"),
            zcode_bin=string("zcode_bin"),
            zcode_workspace=string("zcode_workspace"),
            allow_ollama=bool(arguments.get("allow_ollama")),
            resource=string("resource"),
            ollama_host=None if raw_host in (None, "127.0.0.1") else raw_host,
            ollama_port=port,
            allow_codex=bool(arguments.get("allow_codex")),
            codex_model=string("codex_model"),
            codex_resource=string("codex_resource"),
        )

    def as_run_arguments(self) -> dict[str, object]:
        """The run-style flag mapping for ``build_registry`` validation."""
        return {
            "allow_ollama": self.allow_ollama,
            "resource": self.resource,
            "ollama_host": self.ollama_host,
            "ollama_port": self.ollama_port,
            "allow_codex": self.allow_codex,
            "codex_model": self.codex_model,
            "codex_resource": self.codex_resource,
            "codex_sources": list(self.codex_sources),
            "codex_bin": self.codex_bin,
            "zcode_sources": list(self.zcode_sources),
            "zcode_bin": self.zcode_bin,
            "zcode_workspace": self.zcode_workspace,
        }

    def exec_start_arguments(self) -> list[str]:
        """The selection as ``run`` arguments, in one fixed order."""
        arguments: list[str] = []
        for source_id in self.codex_sources:
            arguments += ["--codex-source", source_id]
        if self.codex_bin is not None:
            arguments += ["--codex-bin", self.codex_bin]
        for source_id in self.zcode_sources:
            arguments += ["--zcode-source", source_id]
        if self.zcode_bin is not None:
            arguments += ["--zcode-bin", self.zcode_bin]
        if self.zcode_workspace is not None:
            arguments += ["--zcode-workspace", self.zcode_workspace]
        if self.allow_ollama:
            if not self.resource:
                raise ValueError("--resource is required with --allow-ollama")
            arguments += ["--allow-ollama", "--resource", self.resource]
            if self.ollama_host is not None:
                arguments += ["--ollama-host", self.ollama_host]
            if self.ollama_port is not None:
                arguments += ["--ollama-port", str(self.ollama_port)]
        if self.allow_codex:
            if not self.codex_model:
                raise ValueError("--codex-model is required with --allow-codex")
            arguments += ["--allow-codex", "--codex-model", self.codex_model]
            if self.codex_resource is not None:
                arguments += ["--codex-resource", self.codex_resource]
        return arguments


# ── Unit rendering ────────────────────────────────────────────────────────────

_SAFE_UNQUOTED = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_./:@%^+=,-"
)


def systemd_quote(word: str) -> str:
    """One systemd unit word in systemd's own parsing rules.

    Every literal ``%`` is doubled first (``%%``): BOTH ``ExecStart``
    and ``ReadWritePaths`` resolve unit specifiers on the raw setting
    value BEFORE quoting is processed, and double quotes never suppress
    that expansion (verified against systemd 255: a literal ``%20`` in
    either setting fails the unit to load with "Invalid specifier",
    quoted or not; ``%%20`` loads and expands back to ``%20``). Unquoted
    when the escaped word consists solely of characters systemd treats
    literally; otherwise double-quoted with C-style escapes for the
    characters systemd would reinterpret. Applied to every path so a
    state directory or workspace with spaces renders a VALID unit, and
    so no value can break out of its word (quotes and backslashes are
    escaped, never passed through). ``$`` is deliberately NOT handled
    here: variable substitution applies only to ``Exec*`` command lines,
    never to ``ReadWritePaths`` — ``render_unit`` handles it once for
    ``ExecStart`` with the documented ``:`` prefix.
    """
    escaped = word.replace("%", "%%")
    if word and all(character in _SAFE_UNQUOTED for character in word):
        return escaped
    escaped = escaped.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_unit(
    *,
    executable: Path,
    state_dir: Path,
    selection: ServiceSelection,
    zcode_state_home: Path | None = None,
) -> str:
    """The deterministic systemd user unit for one paired worker.

    Byte-stable for identical inputs (no timestamps), so idempotency is
    plain content equality. No secret appears anywhere: the pairing
    credential lives only inside the state directory the unit points at.

    ``zcode_state_home`` is the ZCode CLI's resolved state directory and
    is REQUIRED whenever ``selection`` carries a ZCode source (a
    :class:`ValueError` otherwise — the writable-home contract cannot be
    silently omitted), and is ignored for units without one. Both
    systemd substitution layers are handled here: literal ``%`` is
    doubled by :func:`systemd_quote` (specifier expansion applies to
    ``ExecStart`` AND ``ReadWritePaths`` regardless of quoting), and the
    ``ExecStart`` line carries the documented ``:`` executable prefix so
    ``$``-variable substitution is suppressed for the whole command
    line — every word stays the literal path/value it was rendered from
    (``ExecStart`` is not a shell line; ``ReadWritePaths`` never does
    variable substitution, so ``$`` there needs no escaping at all).
    """
    if selection.zcode_sources and zcode_state_home is None:
        # The writable-home contract cannot be silently omitted: a
        # ZCode-source unit without the state home would predictably
        # break every ZCode execution under ProtectHome=read-only.
        raise ValueError(
            "a ZCode source unit requires the resolved ZCode CLI state "
            + "home (install resolves it; render_unit must be called "
            + "with zcode_state_home)"
        )
    persisted_paths = [executable, state_dir]
    persisted_paths.extend(
        Path(value) for value in (
            selection.codex_bin, selection.zcode_bin, selection.zcode_workspace,
        ) if value is not None
    )
    if zcode_state_home is not None:
        persisted_paths.append(zcode_state_home)
    if any(not path.is_absolute() for path in persisted_paths):
        raise ValueError("render_unit requires installation-normalized absolute paths")
    argv = [str(executable), "run", "--state-dir", str(state_dir)]
    argv += selection.exec_start_arguments()
    # The ':' prefix (systemd.service(5) "Command Lines") suppresses
    # environment-variable substitution for the ENTIRE command line: a
    # literal '$' in any path must never silently expand to an
    # environment value — or to nothing. Specifier expansion is NOT
    # suppressed by the prefix, so systemd_quote still doubles '%'.
    exec_start = ":" + " ".join(systemd_quote(word) for word in argv)
    write_paths = [str(state_dir)]
    zcode_writable: list[Path] = []
    if zcode_state_home is not None:
        if not selection.zcode_sources:
            raise ValueError(
                "zcode_state_home is only rendered for ZCode sources"
            )
        # Service mode must not be stricter than a foreground `run`:
        # normal ZCode CLI execution writes its session/runtime/log/
        # rollout and database state under its own supported state home,
        # which ProtectHome=read-only would refuse. Exactly this one
        # resolved directory is the exception — never a writable $HOME.
        zcode_writable.append(zcode_state_home)
    if selection.zcode_workspace:
        zcode_writable.append(Path(selection.zcode_workspace))
    for raw_path in zcode_writable:
        # Rendering serializes the validated values, never filesystem identity.
        value = str(raw_path)
        if value not in write_paths:
            write_paths.append(value)
    read_write_paths = " ".join(systemd_quote(path) for path in write_paths)
    lines = [
        UNIT_MARKER_LINE,
        "# The worker's pairing credential lives only in the state directory",
        "# (0700 tree, 0600 files); no secret is embedded in this unit.",
        "",
        "[Unit]",
        "Description=Scarcity Router native worker (outbound bridge to the router server)",
        f"Documentation={DOCUMENTATION_URL}",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=simple",
        "# ':' prefix: no $-variable substitution on this line — every word",
        "# is the literal path/value rendered below; '%' is written as '%%'.",
        f"ExecStart={exec_start}",
        "# The runtime reconnects with bounded backoff on its own; this",
        "# restart covers process death (crash, exhausted reconnect budget).",
        "Restart=on-failure",
        "RestartSec=5s",
        "# SIGTERM takes the deterministic stop path (stop event, socket",
        "# closed, in-flight attempts cancelled and reported interrupted).",
        "TimeoutStopSec=30s",
        "# Hardening: outbound TCP only; every writable path is listed in",
        "# ReadWritePaths (the worker state directory; for ZCode sources",
        "# also the ZCode CLI's own state home and the authorized workspace).",
        "NoNewPrivileges=true",
        "PrivateTmp=true",
        "ProtectSystem=strict",
        "ProtectHome=read-only",
        f"ReadWritePaths={read_write_paths}",
        "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines)


def unit_install_path(
    *,
    env: Mapping[str, str] | None = None,
    home: Callable[[str], str] | None = None,
) -> Path:
    """The systemd user-unit location: ``$XDG_CONFIG_HOME`` or
    ``~/.config/systemd/user/<unit>`` (the same resolution as
    ``worker_state_dir``, with config in place of data)."""
    environment = os.environ if env is None else env
    xdg_config_home = environment.get("XDG_CONFIG_HOME", "")
    if xdg_config_home and os.path.isabs(xdg_config_home):
        base = Path(xdg_config_home)
    else:
        home_value = environment.get("HOME", "")
        if home_value:
            base = Path(home_value) / ".config"
        else:
            resolve_home = home if home is not None else os.path.expanduser
            base = Path(resolve_home("~")) / ".config"
    return base / "systemd" / "user" / SERVICE_UNIT_NAME


def resolve_zcode_state_home(env: Mapping[str, str] | None = None) -> Path:
    """The EXACT resolved ZCode CLI state directory a ZCode unit allows.

    Service mode is sandboxed with ``ProtectHome=read-only``, and normal
    ZCode CLI execution writes session/runtime/log/rollout and database
    state under its supported state home (``$HOME/.zcode`` — the ZCode
    adapter's own ``HOME`` contract), so a ZCode-source unit must except
    exactly that one directory in ``ReadWritePaths`` — and nothing
    wider. The real directory must already exist: the owner's own
    interactive ZCode usage (the official ``zcode login zai`` sign-in
    path) creates it, and a missing directory would make the unit fail
    to start at all — so install refuses with the remediation instead of
    rendering an impossible path. This tooling never creates ZCode's
    state home and never reads or writes its contents (D-061 constraint 3).
    """
    resolved = Path(os.path.realpath(zcode_state_home(env)))
    if not resolved.is_dir():
        raise ServiceZCodeStateHomeError(
            f"the ZCode CLI state home {resolved} does not exist; run "
            + "the official ZCode CLI once as this user (e.g. 'zcode "
            + "login zai') before installing the service, so the unit "
            + "can grant exactly that one directory write access"
        )
    return resolved


# ── Executable resolution ─────────────────────────────────────────────────────


def resolve_worker_executable(
    argv0: str | None,
    path_lookup: Callable[[str], str | None] = shutil.which,
) -> Path:
    """The ACTUAL installed worker executable for ``ExecStart``.

    The console script or packaged binary this command ran through, when
    it can be used directly (systemd user units have a minimal PATH, so
    the unit carries the resolved absolute path); under
    ``python -m scarcity_router.worker_client`` this falls back to the
    ``scarcity-router-worker`` console script on PATH.
    """
    if argv0:
        invoked = Path(argv0).name
        if invoked == "scarcity-router-worker" or invoked.startswith(
            "scarcity-worker"
        ):
            candidate = Path(argv0).resolve()
            _validate_executable(candidate)
            return candidate
    found = path_lookup("scarcity-router-worker")
    if found is None:
        raise ServiceExecutableError(
            "could not locate the installed worker executable; install the "
            + "package first (uv tool install scarcity-router or pipx "
            + "install scarcity-router) so `scarcity-router-worker` is on PATH"
        )
    candidate = Path(found).resolve()
    _validate_executable(candidate)
    return candidate


def _validate_executable(path: Path) -> None:
    if not path.is_file() or not os.access(path, os.X_OK):
        raise ServiceExecutableError(
            f"the resolved worker executable is not an executable file: {path}"
        )


# ── Tool seams ────────────────────────────────────────────────────────────────


def _service_tool(binary: str, prefix: tuple[str, ...] = ()) -> ServiceTool:
    resolved = shutil.which(binary)
    if resolved is None:
        raise ServiceToolError(
            f"{binary} was not found on PATH; the worker service lifecycle "
            + "requires a systemd user manager (Linux/WSL with systemd "
            + "enabled)"
        )

    def run(arguments: list[str]) -> ServiceToolResult:
        completed = subprocess.run(
            [resolved, *prefix, *arguments],
            capture_output=True,
            text=True,
            check=False,
        )
        raw_args = cast("list[str]", completed.args)
        return ServiceToolResult(
            command=tuple(raw_args),
            returncode=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )

    return run


def default_service_tools() -> ServiceTools:
    """The real ``systemctl --user`` / ``loginctl`` pair."""
    return ServiceTools(
        systemctl=_service_tool("systemctl", ("--user",)),
        loginctl=_service_tool("loginctl"),
    )


def _print_tool_failure(result: ServiceToolResult) -> None:
    detail = result.stderr.strip() or result.stdout.strip()
    suffix = f": {detail}" if detail else f" (exit {result.returncode})"
    print(f"worker service: systemctl failed{suffix}", file=sys.stderr)


# ── Install-time path normalization (resolve once, persist canonical) ────────


def _canonical_existing_directory(flag: str, value: str) -> Path:
    """The canonical absolute directory an operator-supplied path names.

    Relative input is resolved against the INSTALLER's working directory
    and every symlink/``..`` is resolved with ``realpath`` — exactly once,
    here, at install time. Only the canonical absolute result may enter
    the unit: a user manager resolves the service's relative paths against
    its own working-directory context (``/`` by default, not this shell's
    cwd), so a persisted relative or non-canonical path would name a
    DIFFERENT directory after reboot than the one validated here.
    """
    resolved = Path(os.path.realpath(value))
    if not resolved.is_dir():
        raise ServicePathError(
            f"{flag} {value!r} resolves to {resolved}, which is not an "
            + "existing directory; create it (or pass its absolute path) "
            + "and run install again"
        )
    return resolved


def _canonical_pinned_executable(flag: str, value: str) -> Path:
    """The canonical absolute executable an operator pinned by path.

    Same resolve-once discipline as :func:`_canonical_existing_directory`
    (the Daybreak review blocker: a relative or PATH-dependent pinned
    value in the unit would resolve differently under the user manager),
    plus the pinned-target contract the adapters enforce at dispatch: the
    resolved target must be an existing regular executable file. A bare
    command name is refused rather than resolved through the installer's
    ``PATH`` — the unit must never depend on any ``PATH`` at all.
    """
    resolved = Path(os.path.realpath(value))
    if not resolved.is_file() or not os.access(resolved, os.X_OK):
        raise ServicePathError(
            f"{flag} {value!r} resolves to {resolved}, which is not an "
            + "existing regular executable file; pass the absolute path "
            + "of the binary to pin (a bare command name is never "
            + "resolved via PATH for the unit)"
        )
    return resolved


def normalize_selection_paths(selection: ServiceSelection) -> ServiceSelection:
    """Canonicalize EVERY filesystem-valued selection argument.

    The one place a persisted filesystem argument is resolved (the
    Daybreak review blocker: arguments were validated relative to the
    installer process but persisted relative, so systemd later resolved
    them in a different working-directory context). Affected arguments:
    ``--zcode-workspace`` (existing directory), ``--codex-bin`` and
    ``--zcode-bin`` (pinned regular executables). ``--state-dir`` and the
    worker executable are already canonicalized by their own resolvers
    (:func:`_resolved_state_dir`, :func:`resolve_worker_executable`). The
    normalized selection is what gets validated through ``build_registry``
    and what is rendered into the unit, so the validated path, the
    persisted path and the executed path are the same canonical string by
    construction. Relative input stays allowed as UX; only the canonical
    absolute result enters the unit.
    """
    updates: dict[str, object] = {}
    if selection.zcode_workspace is not None:
        updates["zcode_workspace"] = str(
            _canonical_existing_directory("--zcode-workspace", selection.zcode_workspace)
        )
    if selection.codex_bin is not None:
        updates["codex_bin"] = str(
            _canonical_pinned_executable("--codex-bin", selection.codex_bin)
        )
    if selection.zcode_bin is not None:
        updates["zcode_bin"] = str(
            _canonical_pinned_executable("--zcode-bin", selection.zcode_bin)
        )
    return replace(selection, **updates) if updates else selection


# ── Writable-grant policy (small, role-aware; not a sandbox subsystem) ───────


def _canonical_home(env: Mapping[str, str] | None) -> Path:
    """The invoking user's home directory, canonicalized for comparisons."""
    environment = os.environ if env is None else env
    home = environment.get("HOME", "") or os.path.expanduser("~")
    return Path(os.path.realpath(home))


def _refuse_broad_grant(role: str, path: Path, reason: str) -> None:
    raise ServicePathError(
        f"refusing the {role} write grant {path}: {reason}; install wrote "
        + "nothing — choose a dedicated narrower path and run install again"
    )


def validate_writable_grants(
    *,
    state_dir: Path,
    workspace: Path | None,
    zcode_home: Path | None,
    env: Mapping[str, str] | None = None,
) -> None:
    """The role-aware rejection policy for every ``ReadWritePaths`` grant.

    Small and fixed (the Daybreak review blocker; deliberately NOT a
    general-purpose sandbox-policy subsystem):

    - **Universal:** no grant may resolve to the filesystem root or to
      the invoking user's home directory itself.
    - **Worker state directory:** verified separately by
      :func:`scarcity_router.worker_identity_store.open_private_state_dir`
      (existing, owner-owned, not group/world-writable, not root/home) —
      the same policy the single-instance lock enforces at run time.
    - **ZCode state home:** must stay the dedicated ZCode state subtree —
      never the home, never an ancestor of it (``~/.zcode -> $HOME`` or
      ``~/.zcode -> /`` fail installation), never a broad parent of
      another role's grant.
    - **Workspace:** may legitimately live outside ``$HOME``, but never
      the root, never the home (or an ancestor of it), and never a path
      that contains — or equals — the worker state directory (the
      credential store) or the ZCode state home: a broader grant that
      subsumes a narrower boundary is rejected rather than pretending
      three narrow grants still exist. Identical grants are deduplicated
      at render time; containment between roles is rejected here.

    Every refusal names the offending canonical path and the reason and
    happens BEFORE any unit is written or enabled.
    """
    home = _canonical_home(env)
    root = Path(state_dir.anchor)
    if workspace is not None:
        if workspace == root:
            _refuse_broad_grant("workspace", workspace, "it is the filesystem root")
        if workspace == home:
            _refuse_broad_grant(
                "workspace", workspace, "it is the invoking user's home directory itself"
            )
        if home.is_relative_to(workspace):
            _refuse_broad_grant(
                "workspace",
                workspace,
                "it contains the invoking user's home directory (a broad "
                + "ancestor grant, not an application workspace)",
            )
        if state_dir.is_relative_to(workspace):
            _refuse_broad_grant(
                "workspace",
                workspace,
                "it contains or equals the worker state directory "
                + f"{state_dir} (the credential store) — the workspace "
                + "grant would subsume that security boundary",
            )
        if zcode_home is not None and zcode_home.is_relative_to(workspace):
            _refuse_broad_grant(
                "workspace",
                workspace,
                "it contains or equals the ZCode CLI state home "
                + f"{zcode_home} — the workspace grant would subsume "
                + "that boundary",
            )
    if zcode_home is not None:
        if zcode_home == root:
            _refuse_broad_grant(
                "ZCode state home", zcode_home, "it is the filesystem root"
            )
        if zcode_home == home:
            _refuse_broad_grant(
                "ZCode state home",
                zcode_home,
                "it resolves to the invoking user's home directory itself",
            )
        if home.is_relative_to(zcode_home):
            _refuse_broad_grant(
                "ZCode state home",
                zcode_home,
                "it is an ancestor of the invoking user's home directory — "
                + "broader than the dedicated ZCode state subtree",
            )
        if state_dir.is_relative_to(zcode_home):
            _refuse_broad_grant(
                "ZCode state home",
                zcode_home,
                f"it contains or equals the worker state directory {state_dir} "
                + "(the credential store)",
            )
        if workspace is not None and workspace.is_relative_to(zcode_home):
            _refuse_broad_grant(
                "ZCode state home",
                zcode_home,
                f"it contains or equals the authorized workspace {workspace} "
                + "— a broad parent of another role's grant, wider than "
                + "the dedicated ZCode state subtree",
            )


# ── Lifecycle operations ──────────────────────────────────────────────────────


def _resolved_state_dir(arguments: Mapping[str, object]) -> Path:
    raw = arguments.get("state_dir")
    if isinstance(raw, str) and raw:
        return Path(raw).resolve()
    return Path(default_worker_state_dir()).resolve()


def install_service(
    arguments: Mapping[str, object],
    *,
    argv0: str | None,
    tools: ServiceTools,
    open_store: StoreOpener,
    build_registry: RegistryBuilder,
    unit_path: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> int:
    """Generate (or keep) the unit, then daemon-reload + enable --now.

    ``unit_path`` overrides the resolved user-unit location (test seam;
    production always passes ``None`` and installs to the real per-user
    systemd directory). ``env`` overrides the environment the ZCode CLI
    state home is resolved from (test seam; production uses the process
    environment). ``open_store`` and ``build_registry`` are the
    CLI-owned worker seams (pairing check and selection validation).
    """
    state_dir = _resolved_state_dir(arguments)
    # SQLite opens by filename. This complete trusted/private chain excludes
    # cross-principal directory and leaf replacement BEFORE any store access.
    raw_state = arguments.get("state_dir")
    try:
        state_fd = open_private_state_dir(
            state_dir, env=env, create=not (isinstance(raw_state, str) and raw_state)
        )
    except FileNotFoundError:
        raise ServicePathError(
            f"custom worker state directory does not exist: {state_dir}; "
            + "choose an existing private location and pair it before installing"
        ) from None
    try:
        try:
            database = os.stat("worker-state.db", dir_fd=state_fd, follow_symlinks=False)
        except FileNotFoundError:
            pass
        else:
            if not stat.S_ISREG(database.st_mode):
                raise ServicePathError(
                    f"worker database is not a regular file in private state directory "
                    + f"{state_dir}; remove the planted entry and retry"
                )
        store = open_store(str(state_dir))
        try:
            identity = store.load_identity()
        finally:
            store.close()
    finally:
        os.close(state_fd)
    if identity is None:
        print(
            "worker: this worker is not paired yet; pair first — service "
            + "install operates on the paired identity and uses the stored "
            + "server origin",
            file=sys.stderr,
        )
        return 2
    selection = ServiceSelection.from_arguments(arguments)
    # Daybreak blocker: every filesystem-valued argument resolves ONCE,
    # here, to the canonical absolute path that is both validated and
    # persisted — never a relative or PATH-dependent value in the unit.
    selection = normalize_selection_paths(selection)
    # Validate the EXACT configuration the unit will carry, through the
    # same builder `run` uses — an invalid selection never reaches disk.
    _ = build_registry(selection.as_run_arguments(), state_dir=str(state_dir))
    executable = resolve_worker_executable(argv0)
    zcode_home: Path | None = None
    if selection.zcode_sources:
        # Refuses (before anything is written) when the required ZCode
        # CLI state home does not exist — never an impossible
        # ReadWritePaths entry, never a created ZCode state directory.
        zcode_home = resolve_zcode_state_home(env=env)
    workspace: Path | None = (
        Path(selection.zcode_workspace) if selection.zcode_workspace else None
    )
    validate_writable_grants(
        state_dir=state_dir, workspace=workspace, zcode_home=zcode_home, env=env
    )
    unit_text = render_unit(
        executable=executable,
        state_dir=state_dir,
        selection=selection,
        zcode_state_home=zcode_home,
    )
    selected_target = unit_path if unit_path is not None else unit_install_path()
    target = selected_target.parent.resolve() / selected_target.name
    # systemd's search path is implicit, not the canonical string we write.
    # Do not accept an alternate symlink chain that its later lookup could
    # traverse even though our canonical publication directory is trusted.
    if Path(os.path.abspath(selected_target.parent)) != target.parent:
        raise ServicePathError(
            f"service unit directory uses a symlinked path: {selected_target.parent}; "
            + "choose a private canonical configuration location (XDG_CONFIG_HOME) "
            + "so systemd and the installer use the same trusted directory chain"
        )
    dir_fd = _verify_unit_directory(target.parent)
    try:
        existing = _read_unit(dir_fd, target.name)
        if (
            existing is not None
            and existing != unit_text
            and not existing.startswith(UNIT_MARKER_LINE)
        ):
            print(
                "worker: refusing to overwrite an existing unit this tooling "
                + f"did not generate: {target}. Inspect it; if it is an old "
                + "manual copy (formerly examples/scarcity-router-worker.service), "
                + "remove it and run this command again.",
                file=sys.stderr,
            )
            return 2
        if existing == unit_text:
            print(f"worker service: unit already installed (unchanged): {target}")
        else:
            _atomic_write(target, unit_text, dir_fd)
            print(f"worker service: unit written: {target}")
        # Not a validation followed by pathname use: publication already used
        # the retained fd. Detect even same-user swaps before asking systemd
        # to consume a pathname. The trusted chain excludes other-user swaps.
        visible = os.stat(target.parent, follow_symlinks=False)
        retained = os.fstat(dir_fd)
        if (visible.st_dev, visible.st_ino) != (retained.st_dev, retained.st_ino):
            raise ServicePathError(
                f"service unit directory changed during installation: {target.parent}; "
                + "choose a private location and retry"
            )
    finally:
        os.close(dir_fd)
    reloaded = tools.systemctl(["daemon-reload"])
    if reloaded.returncode != 0:
        _print_tool_failure(reloaded)
        return 2
    started = tools.systemctl(["enable", "--now", SERVICE_UNIT_NAME])
    if started.returncode != 0:
        _print_tool_failure(started)
        return 2
    print(f"worker service: enabled and started {SERVICE_UNIT_NAME}")
    _report_linger(tools)
    print(
        f"worker service: paired identity {identity.worker_id}; stored "
        + f"server origin {identity.server_origin}"
    )
    return 0


def status_service(tools: ServiceTools) -> int:
    """One linger line, then the faithful ``systemctl --user status``."""
    _print_linger_state(tools)
    result = tools.systemctl(["status", "--no-pager", SERVICE_UNIT_NAME])
    if result.stdout:
        print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    return result.returncode


def restart_service(tools: ServiceTools) -> int:
    """Restart the unit (the configuration-update application step)."""
    result = tools.systemctl(["restart", SERVICE_UNIT_NAME])
    if result.returncode == 0:
        print(f"worker service: restarted {SERVICE_UNIT_NAME}")
    else:
        if result.stdout:
            print(result.stdout, end="")
        _print_tool_failure(result)
    return result.returncode


def uninstall_service(
    tools: ServiceTools, unit_path: Path | None = None
) -> int:
    """Stop, disable and remove ONLY a unit this tooling generated.

    The paired identity and the worker state directory are deliberately
    kept (uninstalling the service is not unpairing), and linger is
    deliberately left untouched (other units may rely on it).
    """
    target = unit_path if unit_path is not None else unit_install_path()
    if not target.is_file():
        print(
            f"worker service: already uninstalled ({target} does not exist)"
        )
        return 0
    existing = target.read_text(encoding="utf-8")
    if not existing.startswith(UNIT_MARKER_LINE):
        print(
            "worker: refusing to remove a unit this tooling did not "
            + f"generate: {target}. Remove it manually if it is yours.",
            file=sys.stderr,
        )
        return 2
    stopped = tools.systemctl(["disable", "--now", SERVICE_UNIT_NAME])
    if stopped.returncode != 0:
        detail = stopped.stderr.strip() or stopped.stdout.strip()
        suffix = f": {detail}" if detail else ""
        print(
            "worker service: disable/stop reported a problem "
            + f"(continuing with the unit removal){suffix}",
            file=sys.stderr,
        )
    target.unlink()
    reloaded = tools.systemctl(["daemon-reload"])
    if reloaded.returncode != 0:
        _print_tool_failure(reloaded)
    print(
        f"worker service: uninstalled {SERVICE_UNIT_NAME}; the paired "
        + "identity and worker state were kept in the state directory; "
        + "linger was left unchanged"
    )
    return 0


# ── Linger (deliberate and visible) ───────────────────────────────────────────


def _report_linger(tools: ServiceTools) -> None:
    """Check, enable (self) and visibly report loginctl linger.

    A linger failure is NEVER an install failure — the unit is correct
    either way — but it is also never silent: the admin gets the exact
    remediation for headless operation.
    """
    uid = str(os.getuid())
    query = _tool_result_or_failure(
        tools,
        ["show-user", uid, "--property=Linger", "--value"],
    )
    if query.returncode == 0 and query.stdout.strip().lower() == "yes":
        print(
            "worker service: linger is enabled — the worker runs without "
            + "an active login session"
        )
        return
    attempt = _tool_result_or_failure(tools, ["enable-linger", uid])
    if attempt.returncode == 0:
        print(
            "worker service: linger enabled — the worker runs without an "
            + "active login session"
        )
        return
    detail = attempt.stderr.strip() or f"exit {attempt.returncode}"
    print(
        "worker service: linger is NOT enabled (" + detail + "); the "
        + "service only runs while you are logged in. For headless "
        + "operation run once: sudo loginctl enable-linger " + uid,
        file=sys.stderr,
    )


def _print_linger_state(tools: ServiceTools) -> None:
    query = _tool_result_or_failure(
        tools, ["show-user", str(os.getuid()), "--property=Linger", "--value"]
    )
    if query.returncode == 0 and query.stdout.strip().lower() == "yes":
        print("worker service: linger: enabled")
    elif query.returncode == 0:
        print(
            "worker service: linger: not enabled (the service only runs "
            + "while you are logged in; see docs for loginctl enable-linger)"
        )
    else:
        print("worker service: linger: unknown (loginctl unavailable)")


def _tool_result_or_failure(
    tools: ServiceTools, arguments: list[str]
) -> ServiceToolResult:
    try:
        return tools.loginctl(arguments)
    except ServiceToolError as exc:
        return ServiceToolResult(
            command=tuple(arguments), returncode=1, stdout="", stderr=str(exc)
        )


# ── CLI dispatch ──────────────────────────────────────────────────────────────


def run_service_command(
    arguments: Mapping[str, object],
    *,
    argv0: str | None = None,
    tools: ServiceTools | None = None,
    unit_path: Path | None = None,
    env: Mapping[str, str] | None = None,
    open_store: StoreOpener,
    build_registry: RegistryBuilder,
) -> int:
    """The ``service`` subcommand dispatch (the CLI's seam into here).

    Exit codes follow the worker CLI conventions: 0 success (including
    idempotent repeats), 2 refused configuration/failed operation;
    ``status``/``restart`` pass ``systemctl``'s own exit code through.
    ``argv0``, ``tools``, ``unit_path``, ``env``, ``open_store`` and
    ``build_registry`` are injectable seams (tests); production resolves
    the real ones in ``worker_client.main``. A
    :class:`WorkerConfigError` from validation propagates to the CLI's
    existing typed handler.
    """
    resolved_argv0 = sys.argv[0] if argv0 is None else argv0
    resolved_tools = tools if tools is not None else default_service_tools()
    subcommand = arguments.get("service_command")
    try:
        if subcommand == "install":
            return install_service(
                arguments,
                argv0=resolved_argv0,
                tools=resolved_tools,
                open_store=open_store,
                build_registry=build_registry,
                unit_path=unit_path,
                env=env,
            )
        if subcommand == "status":
            return status_service(resolved_tools)
        if subcommand == "restart":
            return restart_service(resolved_tools)
        if subcommand == "uninstall":
            return uninstall_service(resolved_tools, unit_path=unit_path)
        raise ValueError(f"unknown service subcommand: {subcommand!r}")
    except (
        ServiceExecutableError,
        ServiceToolError,
        ServiceZCodeStateHomeError,
        ValueError,
        OSError,
    ) as exc:
        print(f"worker: {exc}", file=sys.stderr)
        return 2


_O_CLOEXEC = getattr(os, "O_CLOEXEC", 0)


def _verify_unit_directory(directory: Path) -> int:
    """Provision through trusted parents and retain the verified unit fd."""
    return open_trusted_worker_directory(directory, create=True)


def _read_unit(dir_fd: int, name: str) -> str | None:
    """Inspect the marker through the same directory identity as publication."""
    try:
        fd = os.open(name, os.O_RDONLY | _O_CLOEXEC | os.O_NONBLOCK, dir_fd=dir_fd)
    except FileNotFoundError:
        return None
    with os.fdopen(fd, "r", encoding="utf-8") as handle:
        if not stat.S_ISREG(os.fstat(handle.fileno()).st_mode):
            raise ServicePathError(f"the existing service unit is not regular: {name}")
        return handle.read()


def _atomic_write(unit_path: Path, unit_text: str, dir_fd: int) -> None:
    """Exclusive temp creation, publication and cleanup on the retained fd."""
    tmp_name = f".{unit_path.name}.tmp-{secrets.token_hex(16)}"
    fd = os.open(
        tmp_name,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | _O_CLOEXEC,
        0o600,
        dir_fd=dir_fd,
    )
    committed = False
    try:
        with os.fdopen(fd, "wb") as handle:
            if not stat.S_ISREG(os.fstat(handle.fileno()).st_mode):
                raise ServicePathError(f"the temporary unit is not regular: {tmp_name}")
            os.fchmod(handle.fileno(), 0o644)
            _ = handle.write(unit_text.encode("utf-8"))
            handle.flush()
            os.fsync(handle.fileno())
        os.rename(
            tmp_name, unit_path.name, src_dir_fd=dir_fd, dst_dir_fd=dir_fd
        )
        committed = True
        try:
            os.fsync(dir_fd)
        except OSError:
            pass  # directory fsync is best-effort where supported
    finally:
        if not committed:
            os.unlink(tmp_name, dir_fd=dir_fd)


__all__ = [
    "DOCUMENTATION_URL",
    "SERVICE_UNIT_NAME",
    "RegistryBuilder",
    "ServiceExecutableError",
    "ServicePathError",
    "ServiceSelection",
    "ServiceTool",
    "ServiceToolError",
    "ServiceToolResult",
    "ServiceTools",
    "ServiceZCodeStateHomeError",
    "StoreOpener",
    "UNIT_MARKER_LINE",
    "default_service_tools",
    "install_service",
    "normalize_selection_paths",
    "render_unit",
    "resolve_worker_executable",
    "resolve_zcode_state_home",
    "restart_service",
    "run_service_command",
    "status_service",
    "systemd_quote",
    "unit_install_path",
    "uninstall_service",
    "validate_writable_grants",
]
