"""The adapter selection persisted in the worker's systemd user unit.

The installed user unit is the persisted home of the operator's adapter
selection (D-065/D-066): ``service install`` renders the selection into
``ExecStart``, and the read-back here parses an installed unit back into
the executable, the worker state directory and the
:class:`ServiceSelection` it runs — the discovery half of ``codex-login``
(``make codex-login``) and of the OpenAI capacity acquisition's
credential-home composition.

This module is deliberately a LEAF next to the worker runtime: it imports
only the standard library and ``worker_local_store`` (the default state
directory). Rendering and the service lifecycle stay in
``worker_service`` (which imports this module for the shared
``ServiceSelection`` type), while ``status`` — which sits BELOW the worker
stack in the import graph (``worker_protocol`` and back through
``selection_app`` import it) — composes the read-back here without
pulling the runtime in.

Two read-back fidelity tiers (D-066, amended on Precision field
evidence):

- a unit this tooling GENERATED (marker first line) is parsed strictly
  against the full documented shape (``parse_exec_start`` — the exact
  inverse of ``worker_service.render_unit``'s rendering);
- a HAND-WRITTEN unit (the retired pre-tooling deployment) is read by a
  targeted flag scan that extracts exactly the login-relevant flags,
  resolves the documented user specifiers exactly (``%h``/``%%``) and
  refuses everything it cannot model exactly.

The marker keeps gating every WRITE (install/uninstall never replace or
remove a unit they did not generate); reading a foreign unit is bounded
to these exact resolutions and refusals. No secret ever enters this
module: the unit embeds none by construction.
"""

from __future__ import annotations

import os
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import cast

from .worker_local_store import default_worker_state_dir

#: The fixed user-unit name: one worker service per user account.
SERVICE_UNIT_NAME = "scarcity-router-worker.service"

#: First line of every unit this tooling generates; the ONLY marker that
#: makes an existing unit ours to replace or remove.
UNIT_MARKER_LINE = (
    "# Managed by Scarcity Router - generated by "
    + "'scarcity-router-worker service install'; do not edit, regenerate."
)


# ── The selection shared by rendering and read-back ───────────────────────────


@dataclass(frozen=True)
class ServiceSelection:
    """The adapter-selection flags the unit's ``ExecStart`` preserves.

    Exactly the ``run`` adapter-selection flags (never ``--server`` or
    ``--label``: the service uses the stored origin and the pairing-time
    identity). Defaults are normalized away so an equivalent re-install
    renders the identical unit.
    """

    codex_sources: tuple[str, ...] = ()
    codex_bin: str | None = None
    zcode_sources: tuple[str, ...] = ()
    zcode_bin: str | None = None
    zcode_workspace: str | None = None
    allow_ollama: bool = False
    resource: str | None = None
    ollama_host: str | None = None
    ollama_port: int | None = None
    allow_codex: bool = False
    codex_model: str | None = None
    codex_resource: str | None = None

    @classmethod
    def from_arguments(cls, arguments: Mapping[str, object]) -> "ServiceSelection":
        """Extract the selection from parsed CLI arguments (no validation)."""

        def string(key: str) -> str | None:
            value = arguments.get(key)
            return value if isinstance(value, str) and value else None

        def strings(key: str) -> tuple[str, ...]:
            value = arguments.get(key)
            if not isinstance(value, list):
                return ()
            items = cast("list[object]", value)
            return tuple(
                item for item in items if isinstance(item, str) and item
            )

        raw_port = arguments.get("ollama_port")
        port: int | None = None
        if isinstance(raw_port, int) and not isinstance(raw_port, bool):
            if raw_port != 11434:
                port = raw_port
        raw_host = string("ollama_host")
        return cls(
            codex_sources=strings("codex_sources"),
            codex_bin=string("codex_bin"),
            zcode_sources=strings("zcode_sources"),
            zcode_bin=string("zcode_bin"),
            zcode_workspace=string("zcode_workspace"),
            allow_ollama=bool(arguments.get("allow_ollama")),
            resource=string("resource"),
            ollama_host=None if raw_host in (None, "127.0.0.1") else raw_host,
            ollama_port=port,
            allow_codex=bool(arguments.get("allow_codex")),
            codex_model=string("codex_model"),
            codex_resource=string("codex_resource"),
        )

    def as_run_arguments(self) -> dict[str, object]:
        """The run-style flag mapping for ``build_registry`` validation."""
        return {
            "allow_ollama": self.allow_ollama,
            "resource": self.resource,
            "ollama_host": self.ollama_host,
            "ollama_port": self.ollama_port,
            "allow_codex": self.allow_codex,
            "codex_model": self.codex_model,
            "codex_resource": self.codex_resource,
            "codex_sources": list(self.codex_sources),
            "codex_bin": self.codex_bin,
            "zcode_sources": list(self.zcode_sources),
            "zcode_bin": self.zcode_bin,
            "zcode_workspace": self.zcode_workspace,
        }

    def exec_start_arguments(self) -> list[str]:
        """The selection as ``run`` arguments, in one fixed order."""
        arguments: list[str] = []
        for source_id in self.codex_sources:
            arguments += ["--codex-source", source_id]
        if self.codex_bin is not None:
            arguments += ["--codex-bin", self.codex_bin]
        for source_id in self.zcode_sources:
            arguments += ["--zcode-source", source_id]
        if self.zcode_bin is not None:
            arguments += ["--zcode-bin", self.zcode_bin]
        if self.zcode_workspace is not None:
            arguments += ["--zcode-workspace", self.zcode_workspace]
        if self.allow_ollama:
            if not self.resource:
                raise ValueError("--resource is required with --allow-ollama")
            arguments += ["--allow-ollama", "--resource", self.resource]
            if self.ollama_host is not None:
                arguments += ["--ollama-host", self.ollama_host]
            if self.ollama_port is not None:
                arguments += ["--ollama-port", str(self.ollama_port)]
        if self.allow_codex:
            if not self.codex_model:
                raise ValueError("--codex-model is required with --allow-codex")
            arguments += ["--allow-codex", "--codex-model", self.codex_model]
            if self.codex_resource is not None:
                arguments += ["--codex-resource", self.codex_resource]
        return arguments


def unit_install_path(
    *,
    env: Mapping[str, str] | None = None,
    home: Callable[[str], str] | None = None,
) -> Path:
    """The systemd user-unit location: ``$XDG_CONFIG_HOME`` or
    ``~/.config/systemd/user/<unit>`` (the same resolution as
    ``worker_state_dir``, with config in place of data)."""
    environment = os.environ if env is None else env
    xdg_config_home = environment.get("XDG_CONFIG_HOME", "")
    if xdg_config_home and os.path.isabs(xdg_config_home):
        base = Path(xdg_config_home)
    else:
        home_value = environment.get("HOME", "")
        if home_value:
            base = Path(home_value) / ".config"
        else:
            resolve_home = home if home is not None else os.path.expanduser
            base = Path(resolve_home("~")) / ".config"
    return base / "systemd" / "user" / SERVICE_UNIT_NAME


# ── Installed-unit read-back ──────────────────────────────────────────────────

#: The selection flags :meth:`ServiceSelection.exec_start_arguments` renders,
#: keyed by their run-flag spelling — the exact vocabulary parse_exec_start
#: accepts back. Anything else fails closed (a unit carrying an unknown flag
#: was rendered by different tooling and is never interpreted by guesswork).
_EXEC_START_APPEND_FLAGS = {
    "--codex-source": "codex_sources",
    "--zcode-source": "zcode_sources",
}
_EXEC_START_VALUE_FLAGS = {
    "--codex-bin": "codex_bin",
    "--zcode-bin": "zcode_bin",
    "--zcode-workspace": "zcode_workspace",
    "--resource": "resource",
    "--ollama-host": "ollama_host",
    "--codex-model": "codex_model",
    "--codex-resource": "codex_resource",
}
_EXEC_START_FLAG_FLAGS = {
    "--allow-ollama": "allow_ollama",
    "--allow-codex": "allow_codex",
}


class ServiceUnitReadError(Exception):
    """The installed unit cannot be read back as our own run configuration
    (safe, actionable message; no secrets — the unit embeds none)."""


@dataclass(frozen=True)
class InstalledServiceConfiguration:
    """What the installed unit actually runs, read back from disk.

    The read-back counterpart of the run configuration the unit carries:
    the executable, the worker state directory and the selection flags
    (the adapter selection the operator installed). ``generated`` records
    which read-back fidelity applied: ``True`` for a unit this tooling
    rendered (parsed strictly against its full documented shape), ``False``
    for a hand-written unit (issue #168 Precision evidence) read by the
    targeted flag scan — same flags, coarser grammar. Consumers that only
    need one configured execution source (e.g. ``codex-login`` discovery)
    read it off ``selection``.
    """

    unit_path: Path
    executable: Path
    state_dir: Path
    selection: ServiceSelection
    generated: bool = True


def _split_exec_start_words(value: str) -> list[str]:
    """Tokenize one ``ExecStart`` VALUE the way systemd splits it.

    Undoes the rendering layers word by word: the ``:`` no-substitution
    prefix, double-quote grouping (with the ``\\`` escapes the renderer
    emits inside quotes) and the ``%%`` specifier unescaping — the exact
    inverse of ``worker_service.systemd_quote``. An unterminated quote
    raises :class:`ServiceUnitReadError`.
    """

    def unescape(text: str) -> str:
        # Exact inverse of the two escape layers systemd_quote applies:
        # ``%%`` back to ``%`` (specifier expansion), and inside quotes
        # ``\\``/``\"`` back to the literal characters. A trailing
        # backslash or lone ``%`` cannot come from our renderer.
        unescaped: list[str] = []
        index = 0
        while index < len(text):
            char = text[index]
            if char == "%" and text[index + 1 : index + 2] == "%":
                unescaped.append("%")
                index += 2
                continue
            unescaped.append(char)
            index += 1
        return "".join(unescaped)

    body = value[1:] if value.startswith(":") else value
    words: list[str] = []
    current: list[str] = []
    has_word = False
    quoted = False
    single_quoted = False
    index = 0
    while index < len(body):
        char = body[index]
        if char == '"' and not single_quoted:
            quoted = not quoted
            has_word = True
            index += 1
        elif char == "'" and not quoted:
            # systemd's single-quote grouping: no escapes inside, the
            # closing quote ends the section. Inside double quotes a
            # single quote is an ordinary literal.
            single_quoted = not single_quoted
            has_word = True
            index += 1
        elif not quoted and not single_quoted and char.isspace():
            if has_word:
                words.append(unescape("".join(current)))
                current = []
                has_word = False
            index += 1
        elif (
            quoted
            and char == "\\"
            and body[index + 1 : index + 2] in ('"', "\\")
        ):
            current.append(body[index + 1])
            has_word = True
            index += 2
        else:
            current.append(char)
            has_word = True
            index += 1
    if quoted or single_quoted:
        raise ServiceUnitReadError("the ExecStart line ends inside a quoted word")
    if has_word:
        words.append(unescape("".join(current)))
    return words


def parse_exec_start(value: str) -> tuple[Path, Path, ServiceSelection]:
    """The inverse of ``worker_service.render_unit``'s ``ExecStart`` rendering.

    Accepts the raw ``ExecStart`` VALUE (the text after ``ExecStart=``),
    tokenizes it the way systemd would (:func:`_split_exec_start_words`)
    and validates the shape every GENERATED unit has
    (``<executable> run --state-dir <dir>`` plus the preserved selection
    flags). Unknown flags, a missing value or a stray positional raise
    :class:`ServiceUnitReadError`: a unit this tooling rendered is never
    interpreted by guesswork.
    """
    words = _split_exec_start_words(value)
    if len(words) < 4 or words[1] != "run" or words[2] != "--state-dir":
        raise ServiceUnitReadError(
            "the ExecStart line does not have the generated "
            + "<executable> run --state-dir <dir> shape"
        )
    executable = Path(words[0])
    state_dir = Path(words[3])
    mapping: dict[str, object] = {}
    index = 4
    while index < len(words):
        word = words[index]
        index += 1
        if word in _EXEC_START_APPEND_FLAGS:
            if index >= len(words):
                raise ServiceUnitReadError(f"{word} has no value in ExecStart")
            values = cast(
                "list[object]", mapping.setdefault(_EXEC_START_APPEND_FLAGS[word], [])
            )
            values.append(words[index])
            index += 1
        elif word in _EXEC_START_VALUE_FLAGS:
            if index >= len(words):
                raise ServiceUnitReadError(f"{word} has no value in ExecStart")
            mapping[_EXEC_START_VALUE_FLAGS[word]] = words[index]
            index += 1
        elif word in _EXEC_START_FLAG_FLAGS:
            mapping[_EXEC_START_FLAG_FLAGS[word]] = True
        elif word == "--ollama-port":
            if index >= len(words):
                raise ServiceUnitReadError(f"{word} has no value in ExecStart")
            try:
                mapping["ollama_port"] = int(words[index])
            except ValueError as exc:
                raise ServiceUnitReadError(
                    f"--ollama-port {words[index]!r} is not an integer"
                ) from exc
            index += 1
        else:
            raise ServiceUnitReadError(
                f"unexpected ExecStart word {word!r}: the installed unit "
                + "was not rendered by this tooling"
            )
    return executable, state_dir, ServiceSelection.from_arguments(mapping)


#: Characters whose presence in a NON-generated unit's ``ExecStart`` means
#: systemd would expand something (a ``$`` variable) or run shell-like
#: syntax the targeted flag scan cannot model exactly. Such a line is
#: refused with the migration recipe, never half-interpreted. The ``%``
#: user specifiers are handled exactly instead (:func:`_expand_user_specifiers`).
_FOREIGN_EXPANSION_CHARACTERS = frozenset("$;|&`")


def _specifier_home(*, env: Mapping[str, str] | None = None) -> str:
    """The user home ``%h`` resolves to — the same source systemd uses.

    A user manager expands ``%h`` to the invoking user's passwd home
    directory; production resolves exactly that. ``env`` overrides the
    resolution (test seam): when an explicit environment mapping is given
    (tests), its ``HOME`` is used.
    """
    if env is not None:
        home_value = env.get("HOME", "")
        if home_value:
            return home_value
    else:
        try:
            import pwd

            entry = pwd.getpwuid(os.getuid())
            if entry.pw_dir:
                return entry.pw_dir
        except (ImportError, KeyError, OSError):
            pass
        home_value = os.environ.get("HOME", "")
        if home_value:
            return home_value
    raise ServiceUnitReadError(
        "the ExecStart line uses the %h specifier but the user's home "
        + "directory cannot be resolved; regenerate the unit with "
        + "'scarcity-router-worker service install --codex-source "
        + "SOURCE_ID' or pass --source"
    )


def _expand_user_specifiers(
    value: str, *, env: Mapping[str, str] | None = None
) -> str:
    """Resolve the systemd user specifiers a hand-written unit may carry.

    The retired example unit anchored every path at ``%h`` (issue #168
    Precision evidence), and specifier expansion applies to the whole
    setting value BEFORE word splitting — so the exact, documented
    resolutions are applied here: ``%%`` to a literal ``%`` and ``%h`` to
    the user's home directory. Any other specifier (``%S``, ``%E``, ``%t``,
    ...) is refused with the migration recipe: its value comes from the
    manager's own environment and guessing it would be half-interpretation.
    """
    expanded: list[str] = []
    index = 0
    while index < len(value):
        char = value[index]
        if char != "%":
            expanded.append(char)
            index += 1
            continue
        following = value[index + 1 : index + 2]
        if following == "%":
            expanded.append("%")
            index += 2
            continue
        if following == "h":
            expanded.append(_specifier_home(env=env))
            index += 2
            continue
        raise ServiceUnitReadError(
            f"the ExecStart line uses the systemd specifier %{following or ''} "
            + "whose value this tooling cannot resolve exactly; regenerate "
            + "the unit with 'scarcity-router-worker service install "
            + "--codex-source SOURCE_ID' (remove the hand-written unit "
            + "first) or pass --source"
        )
    return "".join(expanded)


def _selection_from_foreign_exec_start(
    value: str, *, env: Mapping[str, str] | None = None
) -> tuple[Path, Path, ServiceSelection]:
    """Read the run flags off a HAND-WRITTEN unit's ``ExecStart``.

    Precision's worker (issue #168 field evidence) runs under the retired
    pre-tooling unit shape, so discovery cannot demand the generated
    marker. Instead of refusing the host's only persisted configuration,
    this reads exactly the three flags the login needs (``--codex-source``,
    ``--state-dir``, ``--codex-bin``) off the tokenized command line and
    tolerates wrapper variation (``env``, prefixes) in everything else.
    The fidelity claim stays honest by construction: shell-like syntax and
    ``$`` variables are refused, the ``%h``/``%%`` user specifiers are
    resolved exactly (:func:`_expand_user_specifiers`), a relative
    ``--state-dir`` is refused (systemd resolves it against its own
    working directory), and a line that does not invoke the worker's
    ``run`` command at all is refused — the migration recipe replaces
    every guess.
    """
    for char in sorted(_FOREIGN_EXPANSION_CHARACTERS):
        if char in value:
            raise ServiceUnitReadError(
                f"the ExecStart line uses systemd expansion ({char!r}) that "
                + "cannot be read back exactly; regenerate the unit with "
                + "'scarcity-router-worker service install --codex-source "
                + "SOURCE_ID' (it never replaces a unit it did not generate "
                + "— remove the hand-written unit first) or pass --source"
            )
    if value.rstrip().endswith("\\"):
        raise ServiceUnitReadError(
            "the ExecStart line continues onto another line (trailing "
            + "backslash), which cannot be read back exactly; regenerate "
            + "the unit with 'scarcity-router-worker service install "
            + "--codex-source SOURCE_ID' or pass --source"
        )
    words = _split_exec_start_words(_expand_user_specifiers(value, env=env))
    if "run" not in words:
        raise ServiceUnitReadError(
            "the ExecStart line does not invoke the worker's 'run' "
            + "command; regenerate the unit with 'scarcity-router-worker "
            + "service install --codex-source SOURCE_ID' (remove the "
            + "hand-written unit first) or pass --source"
        )
    sources: list[str] = []
    state_dir: Path | None = None
    codex_bin: str | None = None
    index = 0
    while index < len(words):
        word = words[index]
        index += 1
        if word == "--codex-source":
            if index >= len(words):
                raise ServiceUnitReadError("--codex-source has no value in ExecStart")
            sources.append(words[index])
            index += 1
        elif word == "--state-dir":
            if index >= len(words):
                raise ServiceUnitReadError("--state-dir has no value in ExecStart")
            state_dir = Path(words[index])
            index += 1
        elif word == "--codex-bin":
            if index >= len(words):
                raise ServiceUnitReadError("--codex-bin has no value in ExecStart")
            codex_bin = words[index]
            index += 1
    if state_dir is None:
        # 'run' without --state-dir uses the platform default state
        # directory — derivable exactly, never a guess.
        state_dir = Path(default_worker_state_dir())
    elif not state_dir.is_absolute():
        raise ServiceUnitReadError(
            f"the ExecStart line's --state-dir {str(state_dir)!r} is not "
            + "absolute (systemd would resolve it against its own working "
            + "directory); regenerate the unit with 'scarcity-router-worker "
            + "service install --codex-source SOURCE_ID' or pass --source"
        )
    executable = Path(words[0])
    return (
        executable,
        state_dir,
        ServiceSelection(codex_sources=tuple(sources), codex_bin=codex_bin),
    )


def read_installed_service_configuration(
    *,
    unit_path: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> InstalledServiceConfiguration:
    """Read back the run configuration the INSTALLED unit carries.

    The local discovery half of ``codex-login`` (issue #168): the
    persisted home of the operator's adapter selection is the unit the
    user manager runs, so the source id, state directory and pinned
    Codex binary an operator never has to retype are read from there.
    Two fidelity tiers: a unit this tooling generated (marker first
    line) is parsed strictly against its full documented shape; a
    hand-written unit — Precision's pre-tooling deployment — is read by
    the targeted flag scan
    (:func:`_selection_from_foreign_exec_start`), which refuses anything
    systemd would expand or that does not invoke ``run``. The marker
    keeps gating every WRITE (install/uninstall), exactly as before.
    ``unit_path`` overrides the resolved user-unit location and ``env``
    the home resolution (test seams, mirroring ``install_service``).
    """
    target = unit_path if unit_path is not None else unit_install_path(env=env)
    try:
        text = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise ServiceUnitReadError(
            f"no installed worker service unit found at {target}; install "
            + "the worker service ('scarcity-router-worker service install "
            + "--codex-source SOURCE_ID') or pass the source explicitly"
        ) from None
    except OSError as exc:
        raise ServiceUnitReadError(
            f"the installed worker service unit could not be read: {exc}"
        ) from exc
    lines = text.splitlines()
    generated = bool(lines) and lines[0] == UNIT_MARKER_LINE
    exec_starts = [line for line in lines if line.startswith("ExecStart=")]
    if len(exec_starts) != 1:
        raise ServiceUnitReadError(
            f"{target} does not carry exactly one ExecStart line"
        )
    value = exec_starts[0].removeprefix("ExecStart=")
    if generated:
        executable, state_dir, selection = parse_exec_start(value)
    else:
        executable, state_dir, selection = _selection_from_foreign_exec_start(
            value, env=env
        )
    return InstalledServiceConfiguration(
        unit_path=target,
        executable=executable,
        state_dir=state_dir,
        selection=selection,
        generated=generated,
    )


__all__ = [
    "SERVICE_UNIT_NAME",
    "InstalledServiceConfiguration",
    "ServiceSelection",
    "ServiceUnitReadError",
    "UNIT_MARKER_LINE",
    "parse_exec_start",
    "read_installed_service_configuration",
    "unit_install_path",
]
